name: dartcrawler
description: Asynchronous web-crawler / spidering tool, written in dart.
version: 1.0.0
homepage: https://lambda.black/
author: Gray

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ^0.12.2
  crypto: ^2.1.5

dev_dependencies:
  pedantic: ^1.9.0
